// <auto-generated />
using System;
using DEMO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEMO.Migrations
{
    [DbContext(typeof(DEP_EM_DB))]
    partial class DEP_EM_DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DEMO.Models.DEPARTAMENTO", b =>
                {
                    b.Property<int>("ID_DEPARTAMENTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DEPARTAMENTO"), 1L, 1);

                    b.Property<string>("N_DEPARTAMENTO")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_DEPARTAMENTO");

                    b.HasIndex("ID_DEPARTAMENTO")
                        .IsUnique();

                    b.ToTable("DEPARTAMENTO", "JB");
                });

            modelBuilder.Entity("DEMO.Models.EMPLEADOS", b =>
                {
                    b.Property<int>("ID_EMPLEADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_EMPLEADO"), 1L, 1);

                    b.Property<string>("A_MATERNO")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("A_PATERNO")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("F_NACIMIENTO")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_DEPARTAMENTO")
                        .HasColumnType("int");

                    b.Property<string>("N_EMPLEADO")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("SUELDO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_EMPLEADO");

                    b.HasIndex("ID_DEPARTAMENTO");

                    b.HasIndex("ID_EMPLEADO")
                        .IsUnique();

                    b.ToTable("EMPLEADOS", "JB");
                });

            modelBuilder.Entity("DEMO.Models.EMPLEADOS", b =>
                {
                    b.HasOne("DEMO.Models.DEPARTAMENTO", "DEPARTAMENTO")
                        .WithMany()
                        .HasForeignKey("ID_DEPARTAMENTO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DEPARTAMENTO");
                });
#pragma warning restore 612, 618
        }
    }
}
